### ISSUE TITLE
git lfs error

### ISSUE THREAD

**Issue by peyer** [inferenceengine/shadernn#1]
Downloading core/3rdparty/glfw/lib64/glfw3.dll (226 KB)
Error downloading object: core/3rdparty/glfw/lib64/glfw3.dll (f563382): Smudge error: Error downloading core/3rdparty/glfw/lib64/glfw3.dll (f5633822089c03f6d11442b6a18de2f0f40a7d425552b90bebe64e5e5c93a1bf): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by inferenceengine** [comment]
The LFS bandwidth is increased and it should work now. Thanks.

**Comment by inferenceengine** [comment]
It is verified that the issue is resolved by users.
